# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: sort-simple-yaml
  - id: check-json
  - id: check-merge-conflict
  - id: check-symlinks
  - id: debug-statements
  - id: check-added-large-files
- repo: https://github.com/python-poetry/poetry
  rev: 1.6.0
  hooks:
  - id: poetry-check
  - id: poetry-lock
    # -   id: poetry-publish
- repo: https://github.com/psf/black
  rev: 23.9.1
  hooks:
  - id: black
    args: [--line-length, '120']
- repo: https://github.com/PyCQA/isort
  rev: 5.12.0
  hooks:
  - id: isort
- repo: https://github.com/PyCQA/flake8
  rev: 6.1.0
  hooks:
  - id: flake8
    args: [--max-line-length=120, --extend-ignore=E203]
- repo: https://github.com/PyCQA/pydocstyle
  rev: 6.3.0
  hooks:
  - id: pydocstyle
    args: [--convention=numpy]
    additional_dependencies: [tomli]
- repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
  rev: v2.10.0
  hooks:
  - id: pretty-format-toml
    args: [--autofix, --no-sort]
  - id: pretty-format-yaml
    args: [--autofix]
- repo: https://github.com/mwouts/jupytext
  rev: v1.15.2
  hooks:
  - id: jupytext
    args: [--from, ipynb, --to, md:myst, --sync]
- repo: https://github.com/nbQA-dev/nbQA
  rev: 1.7.0
  hooks:
  - id: nbqa-pyupgrade
    args: [--py310-plus]
  - id: nbqa-black
    args: [--line-length=120]
  - id: nbqa-isort
    args: [--profile=black]
  - id: nbqa-flake8
    args: [--max-line-length=120, --extend-ignore=E203]
- repo: local
  hooks:
  - id: pylint
    name: pylint
    entry: poetry run pylint
    language: system
    types: [python]
    exclude: ^docs/.*
  - id: poetry-export-requirements
    name: poetry-export-requirements
    entry: poetry export --without-hashes --with=main,research -f requirements.txt -o requirements.txt
    language: system
    types: [python]
    pass_filenames: false
  - id: poetry-export-requirements-dev
    name: poetry-export-requirements-dev
    entry: poetry export --without-hashes --only dev -f requirements.txt -o requirements.dev.txt
    language: system
    types: [python]
    pass_filenames: false
  - id: poetry-export-requirements-docs
    name: poetry-export-requirements-docs
    entry: poetry export --without-hashes --only docs -f requirements.txt -o requirements.docs.txt
    language: system
    types: [python]
    pass_filenames: false
