# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.5.0
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: sort-simple-yaml
  - id: check-json
  - id: check-merge-conflict
  - id: check-symlinks
  - id: debug-statements
  - id: check-added-large-files

- repo: https://github.com/python-poetry/poetry
  rev: 1.7.0
  hooks:
  - id: poetry-check
  - id: poetry-lock
    # -   id: poetry-publish

- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.1.11
  hooks:
  - id: ruff  # Run the linter
    args: [--fix]
  - id: ruff-format  # Run the formatter

- repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
  rev: v2.12.0
  hooks:
  - id: pretty-format-toml
    args: [--autofix, --no-sort]
  - id: pretty-format-yaml
    args: [--autofix]

- repo: local
  hooks:
  - id: poetry-export-requirements
    name: poetry-export-requirements
    entry: poetry export --without-hashes --with=main,research -f requirements.txt -o requirements.txt
    language: system
    types: [python]
    pass_filenames: false
  - id: poetry-export-requirements-dev
    name: poetry-export-requirements-dev
    entry: poetry export --without-hashes --only dev -f requirements.txt -o requirements.dev.txt
    language: system
    types: [python]
    pass_filenames: false
