# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: check-yaml
  - id: sort-simple-yaml
  - id: check-json
  - id: pretty-format-json
  - id: check-merge-conflict
  - id: check-symlinks
  - id: debug-statements
  - id: requirements-txt-fixer
  - id: check-added-large-files
- repo: https://github.com/python-poetry/poetry
  rev: 1.6.0
  hooks:
  - id: poetry-check
  - id: poetry-lock
  - id: poetry-export
    name: poetry-export-requirements
    args: [--without-hashes, --only, main, -f, requirements.txt, -o, requirements.txt]
  - id: poetry-export
    name: poetry-export-requirements-dev
    args: [--without-hashes, --only, dev, -f, requirements.txt, -o, requirements.dev.txt]
    # -   id: poetry-publish
- repo: https://github.com/psf/black
  rev: 23.9.1
  hooks:
  - id: black
    args: [--line-length, '120']
- repo: https://github.com/PyCQA/isort
  rev: 5.12.0
  hooks:
  - id: isort
- repo: https://github.com/PyCQA/flake8
  rev: 6.1.0
  hooks:
  - id: flake8
    args: [--max-line-length=120]
- repo: https://github.com/PyCQA/pylint
  rev: v3.0.0
  hooks:
  - id: pylint
    args: [--max-line-length=120]
- repo: https://github.com/PyCQA/pydocstyle
  rev: 6.3.0
  hooks:
  - id: pydocstyle
    args: [--convention=google]
- repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
  rev: v2.10.0
  hooks:
  - id: pretty-format-toml
    args: [--autofix, --no-sort]
  - id: pretty-format-yaml
    args: [--autofix]
