# Model
save_model: true # Save model after training
model_name: human_policy_D99_50S   # Name of saved model
save_model_path: ./models/il/ # Path to save model

# Train
total_samples: 100_000 # Number of obs-act-next_obs-done pairs to generate
n_epochs: 20 # Training epochs
net_arch: [256, 128] # Network architecture

# 5000 samples for 10 scenes
# 20,000 samples for 60 scenes 
# 100,000 samples for 500 scenes