# Model 
save_model: true # Save model after training
model_name: "human_policy_data_2_scenes" # Name of saved model
save_model_path: ./models/il/ # Path to save model

# Train 
total_samples: 10_000 # Number of obs-act-next_obs-done pairs to generate
n_epochs: 100 # Training epochs
