project: hr_ppo_2scenes
env_id: Nocturne
seed: 42
track_wandb: true
wandb_init_videos: [] #['expert', 'expert_discrete']
where_am_i: headless_machine   # Change to "headless_machine" when you're on a cluster or desktop
exp_name: Nocturne
verbose: 0
train_on_single_scene: false

wandb:
  sync_tensorboard: true
  save_code: false

ma_callback:
  log_human_metrics: true
  log_indiv_metrics: false
  log_agent_actions: false
  save_model: true
  model_save_freq: 200 # In iterations (one iter ~ (num_agents x n_steps))
  save_video: true
  record_n_scenes: 2 # Number of different scenes to make videos of 
  video_save_freq: 100 # Make a video every k iterations (one iter is x steps)
  video_deterministic: true

ppo:
  policy: MlpPolicy
  n_steps: 4096
  ent_coef: 0.005 # Default in SB3 is 0
  vf_coef: 0.5 # Default in SB3 is 0.5

learn:
  total_timesteps: 2_000_000
  progress_bar: false

# human-regularized RL
reg_weight: 0.0
human_policy_path: models/il/human_policy_2_scenes_2023_11_22.pt
