project: nocturne_ppo_exp
env_id: Nocturne
seed: 6
track_wandb: true
wandb_init_videos: ['expert', 'expert_discrete']
where_am_i: headless_machine   # Change to "headless_machine" when you're on a cluster or desktop
exp_name: Nocturne

wandb:
  sync_tensorboard: true
  save_code: false

ma_callback:
  log_indiv_metrics: true
  save_model: true
  model_save_freq: 200_000
  save_video: true
  video_save_freq: 20 # Make a video every k iterations (one iter is x steps)
  video_deterministic: false
  metrics_deterministic: false

ppo:
  policy: MlpPolicy
  n_steps: 4096


learn:
  total_timesteps: 10_000_000
  progress_bar: false
