# Base paths 
bc_models_dir: models/il
hr_ppo_models_dir_self_play: models/hr_rl/self_play_s50
wandb_project: prototyping/S50-75/

# The human reference policy used for HR-PPO
used_human_policy: 
  - name: human_policy_D651_S500_02_18_20_05_AV_ONLY
    agent: BC
    train_agent: '-'
    wandb_run: '-'

# HR-PPO models
best_overall_models: 
  - name: policy_L0.0_S50_I2500.zip
    agent: PPO
    reg_weight: 0.0 
    train_agent: Self-play
    wandb_run: good-serenity

  - name: policy_L0.02_S50_I2600.zip
    reg_weight: 0.02
    agent: HR-PPO
    train_agent: Self-play
    wandb_run: sweet-oath-74

  - name: policy_L0.05_S50_I2250.zip
    reg_weight: 0.05
    agent: HR-PPO
    train_agent: Self-play
    wandb_run: 

  - name: policy_L0.06_S50_I2456.zip
    reg_weight: 0.06
    agent: HR-PPO
    train_agent: Self-play
    wandb_run: 
  
  - name: policy_L0.08_S50_I2402.zip
    reg_weight: 0.08
    agent: HR-PPO
    train_agent: Self-play
    wandb_run: celestial-bird-79