# Base paths 
bc_models_dir: 
hr_ppo_models_dir_self_play:

# The human reference policy used for HR-PPO
human_policies: 
  - name: 
    agent: BC
    train_agent: '-'
    wandb_run: '-'

# HR-PPO models
hr_ppo_models: 
  - name: 
    agent: PPO
    reg_weight: 0.0 
    train_agent: Self-play
    wandb_run: 

  