# Base paths 
bc_models_dir: models/il
hr_ppo_models_dir_self_play: models/hr_rl/self_play_paper_final
wandb_project: prototyping/hr_ppo_paper/

# The human reference policy used for HR-PPO
used_human_policy: 
  - name: human_policy_D651_S500_02_18_20_05_AV_ONLY
    agent: BC
    train_agent: '-'
    num_scenes: 200
    wandb_run: '-'

# HR-PPO models
best_overall_models: 
  # - name: policy_L0.0_S100_I400.zip
  #   agent: MA PPO
  #   reg_weight: 0.0 
  #   train_agent: Self-play
  #   num_scenes: 100
  #   wandb_run: happy-armadillo-203

  - name: policy_L0.0_S200_I3000.zip
    agent: PPO
    reg_weight: 0.0 
    train_agent: Self-play
    num_scenes: 200
    wandb_run: toasty-sun-204
  
  # Single agent PPO baseline
  - name: policy_L0.0_S200_I800_single_agent.zip
    agent: PPO
    reg_weight: 0.0 
    train_agent: Log-replay
    num_scenes: 200
    wandb_run: different-waterfall-232

  # - name: policy_L0.02_S200_I1500.zip
  #   agent: HR-PPO 
  #   reg_weight: 0.02
  #   train_agent: Self-play
  #   num_scenes: 200
  #   wandb_run: northern-plasma-191

  # - name: policy_L0.06_S100_I2800.zip
  #   reg_weight: 0.06
  #   agent: MA HR-PPO
  #   train_agent: Self-play
  #   num_scenes: 100
  #   wandb_run: worthy-terrain-211

  # - name: policy_L0.06_S200_I3366.zip
  #   reg_weight: 0.06
  #   agent: HR-PPO
  #   train_agent: Self-play
  #   num_scenes: 200
  #   wandb_run: lunar-plant-212

  # - name: policy_L0.07_S200_I3200.zip
  #   reg_weight: 0.07
  #   agent: HR-PPO
  #   train_agent: Self-play
  #   num_scenes: 200
  #   wandb_run: vague-glade-208

  - name: policy_L0.07_S100_I3065.zip
    reg_weight: 0.07
    agent: HR-PPO
    train_agent: Self-play
    num_scenes: 100
    wandb_run: giddy-bee-207

  # Single agent HR-PPO baseline
  - name: policy_L0.06_S200_I800_single_agent.zip
    reg_weight: 0.06
    agent: HR-PPO
    train_agent: Log-replay
    num_scenes: 200
    wandb_run: solar-snowflake-233

