# Base paths 
bc_models_dir: models/il
hr_ppo_models_dir_self_play: models/hr_rl/self_play

# The human reference policy used for HR-PPO
used_human_policy: 
  - name: human_policy_D403_S500_02_08_21_30
    agent: BC
    train_agent: '-'
    wandb_run: '-'

# HR-PPO models
best_overall_models: 
  - name: policy_L0.0_S100_I1750.zip
    agent: PPO
    reg_weight: 0.0 
    train_agent: Self-play
    wandb_run: 

  - name: policy_L0.01_S100_I2071.zip
    reg_weight: 0.01
    agent: HR-PPO
    train_agent: Self-play
    wandb_run: 

  - name: policy_L0.05_S100_I2000.zip
    reg_weight: 0.05
    agent: HR-PPO
    train_agent: Self-play
    wandb_run: 

  - name: policy_L0.005_S100_I2059.zip
    reg_weight: 0.005
    agent: HR-PPO
    train_agent: Self-play
    wandb_run: 

  - name: policy_L0.025_S100_I2109.zip
    reg_weight: 0.025
    agent: HR-PPO
    train_agent: Self-play
    wandb_run: 
