# Workflow for building Sphinx docs and deploying to GH Pages
name: Build Sphinx docs and deploy to GH Pages

on:
  pull_request:
    branches: [main]
  workflow_dispatch:
    inputs:
      branch:
        description: Branch to build docs for
        required: true
        default: main

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, cancelling in-progress runs.
concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - run: echo "The job was automatically triggered by a ${{ github.event_name }} event."
    - run: echo "This job is now running on a ${{ runner.os }} server."
    - run: echo "Running on branch ${{ github.ref }} of repository ${{ github.repository }}."
    - name: Check out repository code.
      uses: actions/checkout@v3
    - name: Python environment setup
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: Install dependencies.
      run: |
        sudo apt-get update
        sudo apt-get install libsfml-dev
        git submodule sync
        git submodule update --init --recursive
        python -m pip install -U pip poetry
        poetry install --with=docs
    - name: Build Sphinx docs
      run: poetry run sphinx-build -b html ${{ github.workspace }}/docs/source ${{ github.workspace }}/docs/build/html
    - name: Setup Pages
      uses: actions/configure-pages@v3
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v1
      with:
        path: ./docs/build/html     # Upload HTML docs only
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v2
